import MemberInfo from "@/components/page-components/MemberInfo";
import Sidebar from "@/components/page-components/RightSidebar";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import React from "react";

interface PageProps {
  params: {
    id: string;
  };
}

const leaders = [
  {
  id: "1",
  name: "Jienbaev Berdax Kalbay o‘g‘li",
  position: "O'zbekiston Respublikasi Oliy Majlisi Qonunchilik palatasi deputati yordamchisi, mahalliy kengashlar deputatlari va partiya guruhlari bilan ishlash bo‘yicha bosh mutaxassis",
  birthYear: "1996",
  birthPlace: "Nukus shahri",
  nationality: "qoraqalpoq",
  education: "oliy ma'lumotli",
  university: "Qoraqalpoq davlat universiteti (2020), Qoraqalpoq davlat universiteti magistraturasi (2022)",
  specialization: "huquqshunos",
  degree: "yo‘q",
  languages: "rus tili, ingliz tili",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/1. Jiyenbayev Berdakh Kalbay o‘g‘li.JPG",
  articles: []
},

  
    {
  id: "2",
  name: "Hojanova Gulbanu Jengis qizi",
  position: "Biznesni rivojlantirish banki Qoraqalpog‘iston Respublikasi boshqarmasi xodimi",
  birthYear: "2000",
  birthPlace: "Qoraqalpog‘iston Respublikasi, Kegeyli tumani",
  nationality: "qoraqalpoq",
  education: "tugallangan oliy",
  university: "Qoraqalpoq davlat universiteti (2022)",
  specialization: "biologiya",
  degree: "yo‘q",
  languages: "rus tili, ingliz tili",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/2. Khojanova Gul'banu Jenis qizi.JPG",
  articles: []
},

  
  {
  id: "3",
  name: "Bazarbayeva Shakhnoza Sultonbaevna",
  position: "O‘zbekiston davlat san’at va madaniyat instituti Nukus filiali 4-kurs talabasi (sirtqi ta’lim)",
  birthYear: "2003",
  birthPlace: "Qoraqalpog‘iston Respublikasi, Nukus shahri",
  nationality: "qoraqalpoq",
  education: "tugallanmagan oliy",
  university: "O‘zbekiston davlat san’at va madaniyat instituti, Nukus filiali",
  specialization: "dramaturg",
  degree: "yo‘q",
  languages: "rus tili, ingliz tili",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/3. Bazarbayeva Shakhnoza Sultonbayevna.JPG",
  articles: []
},

  {
  id: "4",
  name: "Radjapov Babur Gulamjanovich",
  position: "Swiss International Institute Lausanne talabasi (Shveytsariya)",
  birthYear: "1997",
  birthPlace: "Qoraqalpog‘iston Respublikasi, Nukus shahri",
  nationality: "o‘zbek",
  education: "o‘rta-maxsus va oliy tugallanmagan",
  university: "2016 y. Nukus axborot va kommunikatsiya texnologiyalari kolleji",
  specialization: "IKT-elektronika (kollej), Proekt menejmenti (oliy)",
  degree: "yo‘q",
  languages: "ingliz tili, rus tili",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/4. Radjapov Babur Gulamjanovich.jpg",
  articles: []
},

  {
  id: "5",
  name: "Rasulov Nurullo Ilhomjon o‘g‘li",
  position: "“Renessans” telekanalida “Ovoza” informatsion dasturi muxbiri",
  birthYear: "2002",
  birthPlace: "Andijon viloyati, Andijon shahri",
  nationality: "o‘zbek",
  education: "oliy",
  university: "2024 y. Toshkent shahridagi Britaniya menejment universiteti; 2024 y. Qirolicha Margaret universiteti",
  specialization: "Loyihalar boshqaruvi (BBA Project Management)",
  degree: "yo‘q",
  languages: "rus, ingliz tillari",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/5.Nurullo Rasulov Ilxomjon o‘g‘li.jpg",
  articles: []
  },

  
    {
  id: "6",
  name: "Vohidov Shohjahon Abduvosi o‘g‘li",
  position: "",
  birthYear: "2000",
  birthPlace: "Andijon viloyati",
  nationality: "o‘zbek",
  education: "oliy",
  university: "2023-y. Toshkent davlat yuridik universiteti",
  specialization: "Yurist",
  degree: "yo‘q",
  languages: "rus, ingliz tillari",
  militaryRank: "3-darajali yurist",
  email: "",
  image: "",
  articles: []
},

  {
  id: "7",
  name: "Abdullayev Jahongir Qahramonjon o‘g‘li",
  position: "Andijon tumani 'Gumbaz' MFY yoshlar yetakchisi (2022 yil 21 yanvardan)",
  birthYear: "2002",
  birthPlace: "Andijon viloyati, Andijon tumani",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "O‘sh davlat universiteti, 5-kurs (sirtqi)",
  specialization: "Telestudiya va telejurnalistika, teleboshlovchi",
  degree: "yo‘q",
  languages: "ingliz tili",
  militaryRank: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/7.Abdullayev Jaxongir Qaxramonjon.jpg",
  articles: []
},
{
  id: "8",
  name: "Maxammadaliyev Asadbek Mamarasul o‘g‘li",
  position: "O‘zbekiston Respublikasi Oliy Majlisi Qonunchilik palatasi devoni Matbuot xizmati OAV bilan ishlashni muvofiqlashtirish guruhi birinchi toifali mutaxassisi (2025 yil 16 yanvardan)",
  birthYear: "2002",
  birthPlace: "Andijon viloyati, Shahrixon tumani",
  nationality: "o‘zbek",
  education: "oliy",
  university: "Toshkentdagi xalqaro Webster universiteti (bakalavr)",
  specialization: "xalqaro munosabatlar",
  degree: "yo‘q",
  languages: "rus va ingliz (mukammal)",
  militaryRank: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/8.Maxammadaliyev Asadbek Mamarasul o‘g‘li.jpg",
  articles: []
},
{
  id: "9",
  name: "Mamirjonova Safinozi Khursandbek qizi",
  position: "O‘zbekiston Sharda universiteti talabasi (2021 yildan)",
  birthYear: "2004",
  birthPlace: "Andijon viloyati",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "O‘zbekiston Sharda universiteti",
  specialization: "Amaliy ingliz tili fakulteti, tarjimonlik",
  degree: "yo‘q",
  languages: "rus, ingliz tillari",
  militaryRank: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/9.Mamirjonova Safinozi Xursandbek qizi.jpg",
  articles: []
},
{
  id: "10",
  name: "Abdurahmonov Asadbek Oybek o‘g‘li",
  position: "O‘zbekiston Respublikasi Oliy Majlisi Qonunchilik palatasi Devoni Korruptsiyaga qarshi kurashish va sud-huquq masalalari qo‘mitasi kotibiyatining referenti (2025 yil 17 yanvardan)",
  birthYear: "2000",
  birthPlace: "Andijon viloyati, Marhamat tumani",
  nationality: "o‘zbek",
  education: "oliy",
  university: "Toshkent davlat yuridik universiteti, 2024 (bakalavr)",
  specialization: "yurisprudentsiya",
  degree: "yo‘q",
  languages: "rus va ingliz tillari",
  militaryRank: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/10. AbdurahmonovAsadbek Oybek o‘g‘li.JPG",
  articles: []
},
{
  id: "11",
  name: "Azizova Visola Behzod qizi",
  position: "O‘zbekiston Milliy universiteti talabasi (2023 yil 2 sentabrdan)",
  birthYear: "2004",
  birthPlace: "Andijon viloyati, Andijon shahri",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "O‘zbekiston Milliy universiteti, 2021",
  specialization: "xorijiy til va adabiyot",
  degree: "yo‘q",
  languages: "rus, ingliz tillari",
  militaryRank: "yo‘q",
  awards: "2021 yil — “Kelajak bunyodkori” medali",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/11.Azizova visola.jpg",
  articles: []
},
{
  id: "12",
  name: "Karimov Behruz Baxtiyorovich",
  position: "Toshkent davlat yuridik universiteti 2-kurs talabasi (2022 yil 5 sentabrdan)",
  birthYear: "2005",
  birthPlace: "Buxoro shahri",
  nationality: "o‘zbek",
  education: "o‘rta",
  university: "2022 y., Buxoro shahri 2-maktab",
  specialization: "huquqshunos",
  degree: "yo‘q",
  languages: "rus, ingliz tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/12. Karimov Bexruz Baxtiyorovich.jpg",
  articles: []
},
{
  id: "13",
  name: "Bobojonov Saidjon O‘tkirovich",
  position: "Toshkent irrigatsiya va qishloq xo‘jaligini mexanizatsiyalash muhandislari instituti Milliy tadqiqot universiteti Buxoro tabiiy resurslarni boshqarish instituti iqtidorli talabalar bilan ishlash bo‘limi mutaxassisi (2023 yil 4 oktabrdan)",
  birthYear: "2000",
  birthPlace: "Buxoro viloyati, Buxoro shahri",
  nationality: "o‘zbek",
  education: "oliy",
  university: "Toshkent irrigatsiya va qishloq xo‘jaligini mexanizatsiyalash muhandislari instituti Milliy tadqiqot universiteti Buxoro tabiiy resurslarni boshqarish instituti (2023)",
  specialization: "Yer kadastri bo‘yicha muhandis",
  degree: "yo‘q",
  languages: "rus tili",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/13.Bobojonov Sayidjon.jpg",
  articles: []
},
{
  id: "14",
  name: "Fayziyeva Fotima Tohir qizi",
  position: "O‘zbekiston jurnalistika va ommaviy kommunikatsiyalar universiteti talabasi",
  birthYear: "2002",
  birthPlace: "Buxoro viloyati, Kogon shahri",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Buxoro shahri 8-umumiy ta’lim maktabi",
  specialization: "jurnalist",
  degree: "yo‘q",
  languages: "turk tili",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/14.Fayziyeva Fotima Toxir qizi.JPG",
  party: "O‘zbekiston “Milliy tiklanish” demokratik partiyasi a’zosi",
  deputy: "yo‘q"
},
{
  id: "15",
  name: "Zarifova Sagina Siddiq qizi",
  position: "Yoshlar ishlari agentligida “Seeyouzbekistan” loyiha rahbari",
  birthYear: "2001",
  birthPlace: "Buxoro viloyati, Jondor tumani",
  nationality: "o‘zbek",
  education: "oliy",
  university: "2023 y. Buxoro Davlat Universiteti (kunduzgi), 2023 y. Fransiya Vatel Hotel Management and Tourism High School",
  specialization: "boshqaruvchi (Manager)",
  degree: "yo‘q",
  languages: "ingliz tili, rus tili, fors tili",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/15.Zarifova Sagina Siddik qizi.jpg",
  party: "O‘zbekiston “Milliy tiklanish” demokratik partiyasi",
  deputy: "yo‘q"
},
{
  id: "16",
  name: "Orzikulova Sevinch Jaloliddin qizi",
  position: "Jahon iqtisodiyoti va diplomatiya universiteti talabasi",
  birthYear: "2004",
  birthPlace: "Jizzax viloyati, Jizzax shahri",
  nationality: "o‘zbek",
  education: "Tugallanmagan oliy",
  university: "Xalq ta’limi vazirligi tasarrufidagi filologiya maktabi",
  specialization: "o‘rta",
  degree: "yo‘q",
  languages: "rus, ingliz, turk, fransuz tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/16.Orzikulova Sevinch Jaloliddin qizi.JPG",
  party: "Milliy tiklanish demokratik partiyasi",
  deputy: "yo‘q"
},
{
  id: "17",
  name: "Hakimova Sarvinoz Nodir qizi",
  position: "Raqamli ta’limni rivojlantirish markazi DUK, IT-shaharchalar faoliyatini tashkil etish boshqarmasi bosh mutaxassisi",
  birthYear: "2000",
  birthPlace: "Jizzax viloyati, Forish tumani",
  nationality: "o‘zbek",
  education: "oliy",
  university: "Jizzax davlat pedagogika universiteti (2023)",
  specialization: "pedagogika va psixologiya",
  degree: "yo‘q",
  languages: "rus tili, ingliz tili",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/17.Xakimova Sarvinoz Nodir qizi.jpg",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "18",
  name: "Turg'unova Dilfuza G‘ulom qizi",
  position: "O‘zbekiston XDP Jizzax viloyat Kengashi yoshlar va xotin-qizlar bilan ishlash bo‘limi boshlig‘i",
  birthYear: "1997",
  birthPlace: "Jizzax viloyati, Forish tumani",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Toshkent xalqaro kimyo universiteti, 4-bosqich talabasi (sirtqi)",
  specialization: "boshlang‘ich ta’lim",
  degree: "yo‘q",
  languages: "rus tili",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/18.Turg‘unova Dilfuza G‘ulom qizi.jpg",
  party: "O‘zbekiston XDP",
  deputy: "yo‘q"
},
{
  id: "19",
  name: "Sanaqulov O‘ktoy Muzrob o‘g‘li",
  position: "Toshkent davlat yuridik universiteti 2-kurs talabasi",
  birthYear: "2005",
  birthPlace: "Navoiy viloyati, Nurota tumani",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Toshkent davlat yuridik universiteti",
  specialization: "Yurisprudensiya",
  degree: "yo‘q",
  languages: "ingliz, rus tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/19. Sanakulov O‘ktoy Muzrob o‘g‘li.JPG",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "20",
  name: "Bozorov Jasur Adizqulovich",
  position: "O‘zbekiston XDP Navoiy viloyati kengashi Yoshlar va xotin-qizlar bo‘limi boshlig‘i",
  birthYear: "1999",
  birthPlace: "Navoiy viloyati, Navoiy shahri",
  nationality: "o‘zbek",
  education: "oliy",
  university: "2022 y. Navoiy davlat pedagogika instituti (kunduzgi)",
  specialization: "tarix",
  degree: "yo‘q",
  languages: "rus, ingliz tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "",
  party: "O‘zbekiston XDP",
  deputy: "yo‘q"
},
{
  id: "21",
  name: "Erejepbayev Kuanishbek Tursunovich",
  position: "Toshkent tibbiyot akademiyasi \"Kardiologiya\" yo‘nalishi magistranti",
  birthYear: "1998",
  birthPlace: "Navoiy viloyati, Navoiy tumani",
  nationality: "qoraqalpoq",
  education: "oliy",
  university: "Toshkent tibbiyot akademiyasi Urganch filiali",
  specialization: "davolash ishi",
  degree: "yo‘q",
  languages: "rus, ingliz",
  militaryRank: "yo‘q",
  awards: "O‘zbekiston Respublikasi Prezidenti farmoniga binoan \"Mehr-saxovat\" ko‘krak nishoni, Oliy ta’lim, fan va innovatsiyalar vazirining buyrug‘iga binoan \"Islom Karimov\" nomli davlat stipendiyasi, \"Innovatsion g‘oyalar yetakchisi\" ko‘krak nishoni bilan taqdirlangan",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/21. Erejepbayev Kuanishbek Tursunovich.JPG",
  party: "Milliy tiklanish demokratik partiyasi",
  deputy: "Oliy Majlis Qonunchilik palatasi huzuridagi Yoshlar parlamentiga Navoiy viloyatidan saylangan"
},
{
  id: "22",
  name: "Solijonov Uchkunbek Sadriddinovich",
  position: "Toshkent davlat transport universiteti 3-kurs talabasi",
  birthYear: "2003",
  birthPlace: "Namangan viloyati",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "2020 y. 49-umumiy o‘rta ta’lim maktabi",
  specialization: "siyosatshunoslik",
  degree: "yo‘q",
  languages: "ingliz (B1), rus",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/22. Solijonov Uchqunbek Sadriddinovich.JPG",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "23",
  name: "Ashuraliev Ikromjon Sadirddin o‘g‘li",
  position: "Mirzo Ulug‘bek nomidagi O‘zbekiston Milliy Universiteti talabasi",
  birthYear: "2000",
  birthPlace: "Namangan viloyati, Mingbuloq tumani",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "2021 y. Mirzo Ulug‘bek nomidagi O‘zbekiston Milliy Universiteti (kunduzgi)",
  specialization: "yer usti transport tizimlari va ulardan foydalanish. Avtomobillarga texnik xizmat ko‘rsatish",
  degree: "yo‘q",
  languages: "ingliz tili",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/23. Ashuraliev Ikromjon Sadirddin o‘g‘li.JPG",
  party: "O‘zbekiston XDP",
  deputy: "yo‘q"
},
{
  id: "24",
  name: "Sobitov Mirshod Isoqjon o‘g‘li",
  position: "",
  birthYear: "2003",
  birthPlace: "Namangan viloyati, Uchqo‘rg‘on tumani",
  nationality: "o‘zbek",
  education: "oliy",
  university: "",
  specialization: "siyosatchi",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "rus, ingliz tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/24. Sobitov Mirshod Isoqjon o‘g‘li.jpg",
  party: "yo‘q",
  deputy: "yo‘q"
},
{
  id: "25",
  name: "Nomonjonov Bunyod Baxtiyor o‘g‘li",
  position: "Toshkent davlat transport universiteti magistanti",
  birthYear: "1997",
  birthPlace: "Namangan viloyati, Mingbuloq tumani",
  nationality: "o‘zbek",
  education: "oliy",
  university: "Namanagan muhandislik-qurilish instituti",
  specialization: "yer usti transport tizimlari va ularning ekspluatatsiyasi (transport turlari bo‘yicha)",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "turk tili",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/25. No‘monjonov Bunyod Baxtiyor o‘g‘li.jpeg",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "26",
  name: "Urunov Asadbek Davlatali o‘g‘li",
  position: "Toshkent shahridagi Turin politexnika universiteti, Mashinasozlik texnologiyasi yo‘nalishi talabasi",
  birthYear: "2003",
  birthPlace: "Namangan viloyati",
  nationality: "o‘zbek",
  education: "o‘rta",
  university: "2020 yil, Namangan viloyati Uychi tuman 33-umumta’lim maktabi",
  specialization: "yo‘q",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "ingliz tili",
  militaryRank: "yo‘q",
  awards: "2024 yil — Mard o‘g‘lon davlat mukofoti",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/26. Urunov Asadbek Davlatali o‘g‘li.JPG",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "27",
  name: "Holmirzayeva Odina Sherzod qizi",
  position: "Toshkent davlat iqtisodiyot universiteti talabasi",
  birthYear: "2006",
  birthPlace: "Namangan viloyati, Kosonsoy tumani",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Toshkent davlat iqtisodiyot universiteti",
  specialization: "yo‘q",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "o‘zbek, ingliz, rus, turk, ispan",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/27. Xolmirzayeva Odina Sherzod qizi.jpg",
  party: "yo‘q",
  deputy: "yo‘q"
},
{
  id: "28",
  name: "Amirullaev Azizbek Oybekovich",
  position: "Toshkent davlat sharqshunoslik universitetining talabasi",
  birthYear: "2004",
  birthPlace: "Samarqand viloyati, Samarqand shahri",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Toshkent davlat sharqshunoslik universiteti",
  specialization: "siyosatshunos",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "ingliz, rus tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/28. Amrullayev Azizbek Oybekovich.JPEG",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "29",
  name: "Jumayeva Sevara Samandar qizi",
  position: "Alisher Navoiy nomidagi Toshkent davlat o‘zbek tili va adabiyoti universiteti talabasi",
  birthYear: "2002",
  birthPlace: "Samarqand viloyati, Oqdaryo tumani",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Alisher Navoiy nomidagi Toshkent davlat o‘zbek tili va adabiyoti universiteti",
  specialization: "filologiya (o‘zbek tili va adabiyoti)",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "ingliz, turk tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/29. Jumayeva Sevara Samandar qizi.JPG",
  party: "Milliy tiklanish demokratik partiyasi",
  deputy: "yo‘q"
},
{
  id: "30",
  name: "Ochilov Islombek Bahriddin o‘g‘li",
  position: "O‘zbekiston Jurnalistika va Ommaviy kommunikatsiyalar universiteti talabasi",
  birthYear: "2004",
  birthPlace: "Samarqand viloyati, Kattako‘rgon shahri",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "2021 y. Kattako‘rgon shahri 14-umumta'lim maktabi",
  specialization: "siyosatshunoslik",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "ingliz, turk tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/30. Ochilov Islombek Bahriddin o‘g‘li.JPG",
  party: "yo‘q",
  deputy: "yo‘q"
},
{
  id: "31",
  name: "Hasanov Khurshedjon Zafarjonovich",
  position: "Tadbirkorlar va ishbilarmonlar harakati - O‘zbekiston Liberal-demokratik partiyasi Siyosiy Kengashi Ijroiya qo‘mitasi IT loyihalar menejeri",
  birthYear: "2004",
  birthPlace: "Samarqand viloyati, Samarqand tumani",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "O‘zbekiston jurnalistika va ommaviy kommunikatsiyalar universiteti",
  specialization: "internet jurnalistikasi",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "rus tili, ingliz tili, nemis tili",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/31. Hasanov Khurshedjon Zafarjonovich.jpg",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "32",
  name: "Orifjonov Dalerjon Rustamovich",
  position: "Toshkent tibbiyot akademiyasi 3-kurs talabasi",
  birthYear: "2004",
  birthPlace: "Samarqand viloyati, Samarqand shahri",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Toshkent tibbiyot akademiyasi",
  specialization: "davolash ishi",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "rus tili",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/32. Orifjonov Dalerjon Rustamovich.JPG",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "33",
  name: "Mardonov Muhammad Sanjar o‘g‘li",
  position: "Samarqand viloyati Turizm boshqarmasi kirish, ichki va ziyorat turizmini rivojlantirish bo‘limi bosh mutaxassisi",
  birthYear: "1998",
  birthPlace: "Samarqand viloyati, Pastdarg‘om tumani",
  nationality: "o‘zbek",
  education: "oliy",
  university: "Samarkand iqtisodiyot va servis oliy instituti",
  specialization: "moliyaviy yo‘nalish",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "rus tili, ingliz tili",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "images/yoshlar parlamenti azolari rasmi/1/33. Mardonov Muhammad Sanjar o‘g‘li.JPG",
  party: "O‘zMTDP",
  deputy: "yo‘q"
},
{
  id: "34",
  name: "Suyarov Komiljon Sattarovich",
  position: "Toshkent davlat sharqshunoslik universiteti yoshlar yetakchisi",
  birthYear: "2002",
  birthPlace: "Samarqand viloyati, Toyloq tumani",
  nationality: "o‘zbek",
  education: "oliy",
  university: "Toshkent davlat sharqshunoslik universiteti",
  specialization: "siyosatshunoslik",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "hind, rus va ingliz tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/34. Komiljon Suyarov.JPG",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "35",
  name: "Muradulloyeva Sevinch Soxidjon qizi",
  position: "Samarqand davlat chet tillar instituti talabasi",
  birthYear: "2006",
  birthPlace: "Samarqand viloyati, Urgut tumani",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Samarqand davlat chet tillar instituti",
  specialization: "pedagog (ingliz tili)",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "ingliz, nemis tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/35. Muradillaeva Sevinch Sohibjon qizi.JPG",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "36",
  name: "Irisqulova Kamola Normat qizi",
  position: "Toshkent davlat transport universiteti magistranti, Transport vazirining yo‘l xo‘jaligi sohasida ilmiy ishlar va innovatsiyalar bo‘yicha yordamchisi",
  birthYear: "2000",
  birthPlace: "Sirdaryo viloyati, Oqoltin tumani",
  nationality: "o‘zbek",
  education: "oliy",
  university: "Jizzax politexnika instituti",
  specialization: "quruvchi-muhandis",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "ingliz tili",
  militaryRank: "yo‘q",
  awards: "2024 y. Zulfiyaxonim nomidagi davlat mukofoti",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/36. Irisqulova Kamola Normat qizi.JPG",
  party: "yo‘q",
  deputy: "yo‘q"
},
{
  id: "37",
  name: "Ullaev Otabek Khayrulla o‘g‘li",
  position: "Jahon iqtisodiyoti va diplomatiya universiteti talabasi",
  birthYear: "2006",
  birthPlace: "Sirdaryo viloyati, Guliston shahri",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Jahon iqtisodiyoti va diplomatiya universiteti",
  specialization: "siyosatshunos",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "rus, ingliz tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/37. Asatulayev Otabek.JPG",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "38",
  name: "Abdugafforov Shavkat Komilovich",
  position: "",
  birthYear: "2003",
  birthPlace: "Surxondaryo viloyati, Denov tumani",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Surxondaryo viloyati Denov tumanidagi davlat 2-ixtisoslashtirilgan maktab internati",
  specialization: "Xorijiy mamlakatlar iqtisodiyoti va mamlakatshunoslik",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "rus, ingliz, koreys tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/38. Shavkat Abdug‘afforov Komilovich.JPG",
  party: "Adolat SDP",
  deputy: "yo‘q"
},
{
  id: "39",
  name: "Abdurazakova Rukhshona Ilhomjon qizi",
  position: "Jahon iqtisodiyoti va diplomatiya universiteti 2-kurs talabasi",
  birthYear: "2005",
  birthPlace: "Surxondaryo viloyati",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "TIKXMMI qoshidagi “International House-Tashkent” akademik litseyi",
  specialization: "xalqaro huquq",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "ingliz (C1), rus (B2), fransuz (A2) tillari",
  militaryRank: "yo‘q",
  awards: "2020 y. Zulfiyaxon nomidagi davlat mukofoti",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/39. Abdurazzoqova Ruxshona Ilhomjon qizi.png",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "40",
  name: "Ashurova Maftuna Ortiq qizi",
  position: "Denov tadbirkorlik va pedagogika instituti Raqamli iqtisodiyot kafedrasi stajyor-o‘qituvchisi",
  birthYear: "2000",
  birthPlace: "Surxondaryo viloyati, Sherobod tumani",
  nationality: "o‘zbek",
  education: "oliy",
  university: "2022 y. Termiz davlat universiteti (kunduzgi), 2024 y. Termiz davlat universiteti magistratura",
  specialization: "turizm menejeri",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "ingliz tili",
  militaryRank: "yo‘q",
  awards: "“Kelajak bunyodkori” medali davlat mukofoti",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/40. Ashurova Maftuna Ortik qizi.jpg",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "41",
  name: "Zulkaynarov Sarvar Alisherovich",
  position: "Termiz davlat pedagogika instituti talabasi",
  birthYear: "2005",
  birthPlace: "Surxondaryo viloyati, Jarqo‘rg‘on tumani",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Termiz davlat pedagogika instituti",
  specialization: "tarix",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "rus, ingliz tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/41. Zulqaynarov Sarvar Alisherovich.jpg",
  party: "Milliy tiklanish demokratik partiyasi",
  deputy: "yo‘q"
},
{
  id: "42",
  name: "Mamadiev Islombek Mamadmusa o‘g‘li",
  position: "Mirzo Ulug‘bek nomidagi O‘zbekiston Milliy Universiteti talabasi",
  birthYear: "2003",
  birthPlace: "Surxondaryo viloyati, Oltinsoy tumani",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Mirzo Ulug‘bek nomidagi O‘zbekiston Milliy Universiteti",
  specialization: "siyosatshunoslik",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "ingliz tili",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/42. Mamadiyev Islom Mamatmusa o‘g‘li.JPG",
  party: "O‘zbekiston Xalq demokratik partiyasi",
  deputy: "yo‘q"
},
{
  id: "43",
  name: "Nurullaeva Laylo Khayrullayevna",
  position: "Toshkent davlat agrar universiteti Huquq va turizm fakulteti talaba",
  birthYear: "2002",
  birthPlace: "Surxondaryo viloyati, Termiz shahri",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Toshkent davlat agrar universiteti, Huquq va turizm fakulteti",
  specialization: "yurisprudentsiya (qishloq xo‘jaligi huquqi)",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "rus, ingliz tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/43. Nurullaeva Laylo Khayrullo qizi.JPG",
  party: "Milliy tiklanish demokratik partiyasi",
  deputy: "yo‘q"
},
{
  id: "44",
  name: "Asrorov Zafar Husniddin o‘g‘li",
  position: "O‘zbekiston Milliy universiteti talabasi",
  birthYear: "2001",
  birthPlace: "Toshkent viloyati",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "O‘zbekiston Milliy universiteti",
  specialization: "siyosatshunoslik",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "rus, ingliz tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/44. Asrorov Zafar Husniddin o‘g‘li.JPG",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "45",
  name: "Makhamatqulova Sabrinakhon Abulqosim qizi",
  position: "Jahon iqtisodiyoti va diplomatiya universiteti talabasi",
  birthYear: "2006",
  birthPlace: "Toshkent viloyati, Ohangaron tumani",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Jahon iqtisodiyoti va diplomatiya universiteti",
  specialization: "laborant-analitik",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "rus, ingliz, turk tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/45. Maxambatqulova Sabrina Abulqosim qizi.jpg",
  party: "O‘zbekiston XDP",
  deputy: "yo‘q"
},
{
  id: "46",
  name: "Abduqahhorov Bekzod O‘tkir o‘g‘li",
  position: "Toshkent davlat iqtisodiyot universiteti magistranti",
  birthYear: "2001",
  birthPlace: "Toshkent viloyati",
  nationality: "o‘zbek",
  education: "oliy",
  university: "Toshkent moliya instituti (bakalavr), hozirda Toshkent davlat iqtisodiyot universiteti magistranti",
  specialization: "iqtisodchi",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "rus, ingliz tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/46. Abduqahhorov Bekzod O‘tkir o‘g‘li.jpg",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "47",
  name: "Abdumajitov Muslim Mirmaksud o‘g‘li",
  position: "Sharqshunoslik universiteti talabasi",
  birthYear: "2003",
  birthPlace: "Toshkent viloyati, Bekobod shahri",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Sharqshunoslik universiteti",
  specialization: "turizm",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "rus, ingliz tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/47. Abdumajitov Muslim Mirmaqsud o‘g‘li.jpg",
  party: "O‘zbekiston Ekologik partiyasi",
  deputy: "yo‘q"
},
{
  id: "48",
  name: "Sobirov Umarjon Umid o‘g‘li",
  position: "Toshkent davlat yuridik universiteti Xalqaro huquq va qiyosiy huquqshunoslik fakulteti tyutori",
  birthYear: "2002",
  birthPlace: "Toshkent viloyati, Qibray tumani",
  nationality: "o‘zbek",
  education: "oliy",
  university: "Toshkent davlat yuridik universiteti",
  specialization: "huquqshunos",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "rus, ingliz tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/48. Sobirov Umarjon Umid o‘g‘li.jpg",
  party: "Adolat sotsial-demokratik partiyasi",
  deputy: "yo‘q"
},
{
  id: "49",
  name: "Abdulxayev Javohirbek Taxirovich",
  position: "Plexanova nomidagi Rossiya iqtisodiyot universiteti Toshkent filiali talabasi",
  birthYear: "2004",
  birthPlace: "Toshkent viloyati, Bekobod shahri",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Plexanova nomidagi Rossiya iqtisodiyot universiteti Toshkent filiali",
  specialization: "iqtisod",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "rus tili",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/49. Abdulhaev Javohir Tahirovich.jpg",
  party: "Milliy tiklanish demokratik partiyasi",
  deputy: "yo‘q"
},
{
  id: "50",
  name: "Arabxonova Munisaxon Hojiakbarxon qizi",
  position: "Nizomiy nomidagi Toshkent davlat pedagogika universiteti talabasi",
  birthYear: "2006",
  birthPlace: "Toshkent shahri, Chilonzor tumani",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Nizomiy nomidagi Toshkent davlat pedagogika universiteti",
  specialization: "oligofrenopedagog",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "yo‘q",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/50. Arabxonova Munisaxon Hojiakbarxon qizi.JPG",
  party: "Milliy tiklanish demokratik partiyasi",
  deputy: "yo‘q"
},
{
  id: "51",
  name: "Rahimov Islomjon Shovkatjon o‘g‘li",
  position: "Islom Karimov nomidagi Toshkent davlat texnika universiteti Qo‘qon filiali bitiruvchisi, Prezident huzuridagi Davlat boshqaruv akademiyasi malaka oshiruvchisi",
  birthYear: "2001",
  birthPlace: "Farg‘ona viloyati, Dang‘ara tumani",
  nationality: "o‘zbek",
  education: "oliy",
  university: "Islom Karimov nomidagi Toshkent davlat texnika universiteti Qo‘qon filiali",
  specialization: "injiner",
  degree: "bakalavr",
  academicTitle: "yo‘q",
  languages: "rus, ingliz tillari",
  militaryRank: "yo‘q",
  awards: "O‘zbekiston Respublikasi Ilm-ma’rifat markazining “Yurt iftixori” ko‘krak nishoni",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/51. Rahimov Islomjon Shavkatjon o‘g‘li.jpg",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "52",
  name: "Toshmatov Dilmurod Fazliddin o‘g‘li",
  position: "O‘zbekiston Respublikasi Oliy Majlisi Qonunchilik palatasi Devoni Yuridik boshqarmasi Davlat va jamiyat qurilishi sohasidagi qonunchilik sektori referenti",
  birthYear: "2001",
  birthPlace: "Farg‘ona viloyati, Quva shahri",
  nationality: "o‘zbek",
  education: "oliy",
  university: "Toshkent davlat yuridik universiteti",
  specialization: "yurisprudentsiya",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "rus, ingliz tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/52. Toshmatov Dilmurod Fazliddin o‘g‘li.JPG",
  party: "###",
  deputy: "yo‘q"
},
{
  id: "53",
  name: "Qodirova Sevaraxon Zoyirjon qizi",
  position: "Toshkent davlat yuridik universiteti 4-kurs talabasi",
  birthYear: "2002",
  birthPlace: "Farg‘ona viloyati, Farg‘ona shahri",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Toshkent davlat yuridik universiteti",
  specialization: "yurisprudentsiya",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "ingliz, rus tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/53. Qodirova Sevaraxon Zoyirjon qizi.JPG",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "54",
  name: "O‘ktamov Shohrukhbek Ulug‘bek o‘g‘li",
  position: "O‘zbekiston XDP Farg‘ona viloyat kengashi raisi",
  birthYear: "1996",
  birthPlace: "Farg‘ona viloyati, Rishton tumani",
  nationality: "o‘zbek",
  education: "oliy",
  university: "Koreya Xalqaro universiteti, Farg‘ona shahri",
  specialization: "arxitektura muhandisligi",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "koreys tili",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/54. O‘ktamov Shohruh Ulug‘bek o‘g‘li.JPG",
  party: "O‘zbekiston XDP",
  deputy: "yo‘q"
},
{
  id: "55",
  name: "Dilmurodov Dilmurod Dilshodjon o‘g‘li",
  position: "O‘zbekiston bolalar tashkiloti Xalqaro hamkorlik va grant loyihalari bilan ishlash bo‘limi boshlig‘i",
  birthYear: "2003",
  birthPlace: "Farg‘ona viloyati, Marg‘ilon shahri",
  nationality: "o‘zbek",
  education: "oliy",
  university: "Jahon iqtisodiyoti va diplomatiya universiteti",
  specialization: "siyosatshunos",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "rus, ingliz, nemis tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/55. Dilmurodov Dilmurod.JPG",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "56",
  name: "Sirojiddinov Ayubxon Akmaljon o‘g‘li",
  position: "Toshkent tibbiyot akademiyasi talabasi",
  birthYear: "2004",
  birthPlace: "Farg‘ona viloyati, Qo‘qon shahri",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Toshkent tibbiyot akademiyasi",
  specialization: "o‘rta",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "rus, ingliz tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/56. Sirojiddinov Ayubxon Akmaljon o‘g‘li.JPG",
  party: "Milliy tiklanish demokratik partiyasi",
  deputy: "yo‘q"
},
{
  id: "57",
  name: "Abdurazakov Abdullaziz Akbarjon o‘g‘li",
  position: "",
  birthYear: "2000",
  birthPlace: "Farg‘ona viloyati, Farg‘ona shahri",
  nationality: "o‘zbek",
  education: "oliy",
  university: "Toshkent davlat yuridik universiteti; Jahon iqtisodiyoti va diplomatiya universiteti; Penn State University (AQSH)",
  specialization: "yurisprudentsiya, xalqaro huquq (sohalar bo‘yicha)",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "rus tili, ingliz tili (IELTS 8)",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/57. Abdulaziz Abdurazzoqov Akbarjon o‘g‘li.jpg",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "58",
  name: "Butahonov Ziyodulla Zoirjon o‘g‘li",
  position: "Innovatsion rivojlanish agentligi Milliy ofisi yetakchi ilmiy hodimi",
  birthYear: "1998",
  birthPlace: "Farg‘ona viloyati, Quva tumani",
  nationality: "o‘zbek",
  education: "tugallanmagan oliy",
  university: "Quva tuman qishloq xo‘jaligi kolleji (2016)",
  specialization: "IT",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "rus, xitoy tillari",
  militaryRank: "yo‘q",
  awards: "2022 y. – “Kelajak bunyodkori” medali",
  email: "",
  image: "",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "59",
  name: "Yarasheva Aziza Alisher qizi",
  position: "Hazorasp tuman “Inson” ijtimoiy xizmatlar markazi Shodi xurram MFY kompleks ijtimoiy xizmat ko‘rsatuvchi xodim",
  birthYear: "2000",
  birthPlace: "Xorazm viloyati, Hazorasp tumani",
  nationality: "o‘zbek",
  education: "oliy",
  university: "Toshkent davlat sharqshunoslik universiteti",
  specialization: "siyosatshunoslik",
  degree: "yo‘q",
  academicTitle: "yo‘q",
  languages: "turk va ingliz tillari",
  militaryRank: "yo‘q",
  awards: "yo‘q",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/59. Yarasheva Aziza Alisher qizi.JPG",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},
{
  id: "60",
  name: "Bazarbayev Sardor Urinboevich",
  position: "Ijod va ixtisoslashtirilgan maktablarni rivojlantirish agentligi Olimpiadalarni tashkil qilish sho‘basi mudiri",
  birthYear: "1996",
  birthPlace: "Xorazm viloyati, Gurlan tumani",
  nationality: "o‘zbek",
  education: "oliy",
  university: "O‘zbekiston Milliy universiteti",
  specialization: "matematika",
  degree: "magistr",
  academicTitle: "yo‘q",
  languages: "ingliz tili, rus tili",
  militaryRank: "yo‘q",
  awards: "2017 y. “O‘zbekiston belgisi” ko‘krak nishoni; 2019 y. Mard o‘g‘lon Davlat mukofoti; 2020 y. O‘zbekiston Respublikasi Prezidenti stipendiyasi; 2021 y. “Xalq taʼlimi aʼlochisi” ko‘krak nishoni",
  email: "",
  image: "/images/yoshlar parlamenti azolari rasmi/1/60. Sardor Bazarbayev.jpg",
  party: "O‘zLiDeP",
  deputy: "yo‘q"
},


















































];

const MemberDetail = ({ params }: PageProps) => {
  const member = leaders.find((leader) => leader.id === params.id);
  return (
    <main className="min-h-screen bg-gray-50 pb-16">
      <div className="container mx-auto px-4 py-8">
        <div className="mb-6">
          <Link
            href="/yoshlar-parlamenti-azolari"
            className="inline-flex items-center text-blue-600 hover:underline"
          >
            <ArrowLeft className="h-4 w-4 mr-2" />
            Ortga qaytish
          </Link>
        </div>

        <div className="flex flex-col md:flex-row gap-8">
          {member ? (
            <MemberInfo member={member} />
          ) : (
            <div className="text-lg">A'zo topilmadi.</div>
          )}
          <Sidebar />
        </div>
      </div>
    </main>
  );
};

export default MemberDetail;
